In [1]:
# !pip install -U scikit-learn

ERROR: Could not find a version that satisfies the requirement scikit-learn==0.21.0 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.1, 0.21.2, 0.21.3, 0.22, 0.22.1, 0.22.2, 0.22.2.post1, 0.23.0, 0.23.1, 0.23.2, 0.24.0, 0.24.1, 0.24.2, 1.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0rc1, 1.2.0, 1.2.1, 1.2.2)
ERROR: No matching distribution found for scikit-learn==0.21.0


In [2]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.2.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: None
Author-email: None
License: new BSD
Location: /home/yorinori/anaconda3/lib/python3.8/site-packages
Requires: numpy, threadpoolctl, joblib, scipy
Required-by: 


## 02.02 Obtendo a base de dados

In [3]:
import pandas as pd

dados = pd.read_csv('data/creditcard.csv')
dados.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

## 02.03 Analisando a base de dados

In [4]:
print(dados.isna().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64


In [5]:
n_trasacoes = dados['Class'].count()
n_fraudes = dados['Class'].sum()
n_normais = n_trasacoes - n_fraudes
fraudes_porc = n_fraudes / n_trasacoes
normais_porc = n_normais / n_trasacoes

print("Número de transações: ", n_trasacoes)
print("Número de fraudes: ", n_fraudes, "%.2f" %(fraudes_porc * 100))
print("Número de transações normais: ", n_normais, "%.2f" %(normais_porc * 100))


Número de transações:  284807
Número de fraudes:  492 0.17
Número de transações normais:  284315 99.83


O resultado mostra que os dados são desbalanceados.  Há uma alta porcentagem de transações normais e uma pequena porcentagem de transações que são fraudes.

## 02.05 Criando uma Árvore de Decisão com scikit-learn

In [6]:
X = dados.drop('Class', axis=1).values
y = dados['Class'].values

In [7]:
from sklearn.model_selection import StratifiedShuffleSplit

validador = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)

for treino_id, teste_id in validador.split(X, y):
    X_train, X_test = X[treino_id], X[teste_id]
    y_train, y_test = y[treino_id], y[teste_id]

In [8]:
from sklearn import tree

classificador_arvore_decisao = tree.DecisionTreeClassifier()
arvore = classificador_arvore_decisao.fit(X_train, y_train)
y_pred = arvore.predict(X_test)

## 02.06 Gerando uma imagem da árvore

In [9]:
from sklearn.model_selection import StratifiedShuffleSplit

def validador(X, y):
    validador = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)

    for treino_id, teste_id in validador.split(X, y):
        X_train, X_test = X[treino_id], X[teste_id]
        y_train, y_test = y[treino_id], y[teste_id]
    
    return X_train, X_test, y_train, y_test

In [10]:
%%time
from sklearn import tree

def executar_classificador(classificador, X_train, X_test, y_train):
    arvore = classificador_arvore_decisao.fit(X_train, y_train)
    y_pred = arvore.predict(X_test)

    return y_pred

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 8.82 µs


In [11]:
X = dados.drop('Class', axis=1).values
y = dados['Class'].values

X_train, X_test, y_train, y_test = validador(X, y)

classificador_arvore_decisao = tree.DecisionTreeClassifier()
y_pred_arvore_decisao = executar_classificador(classificador_arvore_decisao, X_train, X_test, y_train)

## 02.07 Visualizando os nós e atributos

In [12]:
import matplotlib.pyplot as plt

def salvar_arvore(classificador, nome):
    plt.figure(figsize=(200, 100))
    tree.plot_tree(classificador, filled=True, fontsize=14)
    plt.savefig(nome)
    plt.close

In [13]:
# execução do validador
X = dados.drop('Class', axis=1).values
y = dados['Class'].values

X_train, X_test, y_train, y_test = validador(X, y)


In [14]:
# execução do classificador DecisionTreeClassifier

# classificador_arvore_decisao = tree.DecisionTreeClassifier()
# y_pred_arvore_decisao = executar_classificador(classificador_arvore_decisao, X_train, X_test, y_train)

In [15]:
# criação da figura da árvore de decisão

# salvar_arvore(classificador_arvore_decisao, "arvore_decisao1.png")

## 03.02 Medindo a Acurácia da Árvore

In [16]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

def validar_arvore(y_test, y_pred):
    print(accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

In [17]:
# validação da árvore de decisão

validar_arvore(y_test, y_pred_arvore_decisao)

0.9990519995786665
[[28419    13]
 [   14    35]]


## 03.03 Medindo além da acurácia

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score

def validar_arvore(y_test, y_pred):
  print(accuracy_score(y_test, y_pred))
  print(precision_score(y_test, y_pred))
  print(confusion_matrix(y_test, y_pred))

In [19]:
# validação da árvore de decisão

validar_arvore(y_test, y_pred_arvore_decisao)

0.9990519995786665
0.7291666666666666
[[28419    13]
 [   14    35]]


In [20]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

def validar_arvore(y_test, y_pred):
  print(accuracy_score(y_test, y_pred))
  print(precision_score(y_test, y_pred))
  print(recall_score(y_test, y_pred))
  print(confusion_matrix(y_test, y_pred))

In [21]:
# validação da árvore de decisão

validar_arvore(y_test, y_pred_arvore_decisao)

0.9990519995786665
0.7291666666666666
0.7142857142857143
[[28419    13]
 [   14    35]]


## 03.04 Analisando as características da árvore

In [22]:
print(classificador_arvore_decisao)
print(classificador_arvore_decisao.get_depth())


DecisionTreeClassifier()
21


Limitando a profundidade da árvore em 10 níveis

In [23]:
%%time
# execução do classificador DecisionTreeClassifier

classificador_arvore_decisao = tree.DecisionTreeClassifier(max_depth=10, random_state=0)
y_pred_arvore_decisao = executar_classificador(classificador_arvore_decisao, X_train, X_test, y_train)

CPU times: user 10.1 s, sys: 0 ns, total: 10.1 s
Wall time: 10.1 s


In [24]:
# validação da árvore de decisão

validar_arvore(y_test, y_pred_arvore_decisao)

0.9994733330992591
0.9473684210526315
0.7346938775510204
[[28430     2]
 [   13    36]]


Colocando limite mínimo de 10 transações por folha

In [25]:
# execução do classificador DecisionTreeClassifier

classificador_arvore_decisao = tree.DecisionTreeClassifier(max_depth=10, random_state=0, min_samples_leaf=10)
y_pred_arvore_decisao = executar_classificador(classificador_arvore_decisao, X_train, X_test, y_train)

In [26]:
# validação da árvore de decisão

validar_arvore(y_test, y_pred_arvore_decisao)

0.9993679997191109
0.8604651162790697
0.7551020408163265
[[28426     6]
 [   12    37]]


## 04.02 Aprendendo o que são os modelos ensemble

In [27]:
# execução do classificador DecisionTreeClassifier com depth = 5

classificador_arvore_decisao = tree.DecisionTreeClassifier(max_depth=5, random_state=0)
y_pred_arvore_decisao = executar_classificador(classificador_arvore_decisao, X_train, X_test, y_train)

In [28]:
# validação da árvore de decisão

validar_arvore(y_test, y_pred_arvore_decisao)

0.999403110845827
0.9210526315789473
0.7142857142857143
[[28429     3]
 [   14    35]]


## 04.03 Entendendo a técnica Bagging e o Random Forest

*Bagging* é uma técnica de *ensemble learning*, que é muito popular principalmente por causa do algoritmo random forest. O *bagging* significa *bootstrapping aggregating*. 

## 04.04 Executando o Random Forest com o scikit-learn

In [29]:
%%time
from sklearn.ensemble import RandomForestClassifier

classificador_random_forest = RandomForestClassifier(n_estimators=100, random_state=0)
y_pred_random_forest = executar_classificador(classificador_random_forest, X_train, X_test, y_train)

CPU times: user 5.08 s, sys: 3.99 ms, total: 5.09 s
Wall time: 5.1 s


In [31]:
salvar_arvore(classificador_random_forest.estimators_[0], "random_forest1")

AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'

In [32]:
validar_arvore(y_test, y_pred_random_forest)

0.999403110845827
0.9210526315789473
0.7142857142857143
[[28429     3]
 [   14    35]]


In [29]:
%%time
from sklearn.ensemble import RandomForestClassifier

classificador_random_forest = RandomForestClassifier(n_estimators=50, random_state=0, max_depth=10)
y_pred_random_forest = executar_classificador(classificador_random_forest, X_train, X_test, y_train)

CPU times: user 5.1 s, sys: 15.9 ms, total: 5.12 s
Wall time: 5.18 s


In [30]:
validar_arvore(y_test, y_pred_random_forest)

0.999403110845827
0.9210526315789473
0.7142857142857143
[[28429     3]
 [   14    35]]


## 05.02 Entendendo a técnica boosting e o AdaBoost

A técnica *boosting*, diferentemente da técnica *bagging* que se baseava em gerar modelos independentes, ou seja, árvores independentes umas das outras e a ideia era que elas fossem mais independentes possíveis. Na técnica *boosting* nós geramos árvores que se completam, ou seja, uma depende da outra. No geral, ela forma um modelo sequencial. Dentro da técnica *boosting* temos um algoritmo que é bem famoso, que eu o **AdaBoost**, “ada” vem de adaptativo. Ou seja, toda vez que uma nova árvore é gerada, ela vai tentar corrigir os erros que a árvore anterior fez, então a ideia é que nós vamos gerando um modelo sequencial de forma que um depende do outro e que um corrija os erros do anterior, até chegarmos no final e termos um resultado bom.

## 05.03 AdaBoost: calculando a influência da árvore

Influência da Árvore:

$\alpha = \frac{1}{2}log\left(\frac{1-\textrm{Erro Total}}{\textrm{Erro Total}}\right)$

## 05.04 AdaBoost: calculando o peso das instâncias

fórmula também para recalcular esses pesos

$w_i = w_{i-1} * e^{\pm \alpha}$

$w$ é o peso e $\alpha$ é a influência da árvore

## 05.05 AdaBoost: Reagrupando a base de dados

Agora já recalculamos o peso das instâncias. Como vamos utilizar isso na nossa fórmula? Qual é o próximo passo agora? Então vai ser da seguinte maneira: o que vamos fazer é construir uma nova base de dados a partir desta.

**Ver video da aula para explicação**

## 05.06 Executando o AdaBoost com o scikit-learn

In [34]:
%%time
from sklearn.ensemble import AdaBoostClassifier

classificador_adaboost = AdaBoostClassifier(random_state=0, n_estimators=100)
y_pred_adaboost = executar_classificador(classificador_adaboost, X_train, X_test, y_train)


CPU times: user 4.83 s, sys: 0 ns, total: 4.83 s
Wall time: 4.83 s


In [32]:
salvar_arvore(classificador_adaboost.estimators_[0], "adaboost1")
salvar_arvore(classificador_adaboost.estimators_[1], "adaboost2")

AttributeError: 'AdaBoostClassifier' object has no attribute 'estimators_'

In [37]:
validar_arvore(y_test, y_pred_adaboost)

0.999403110845827
0.9210526315789473
0.7142857142857143
[[28429     3]
 [   14    35]]


In [38]:
%%time
from sklearn.ensemble import AdaBoostClassifier

classificador_adaboost = AdaBoostClassifier(random_state=0, n_estimators=200)
y_pred_adaboost = executar_classificador(classificador_adaboost, X_train, X_test, y_train)

CPU times: user 5.12 s, sys: 3.94 ms, total: 5.12 s
Wall time: 5.12 s


In [39]:
validar_arvore(y_test, y_pred_adaboost)

0.999403110845827
0.9210526315789473
0.7142857142857143
[[28429     3]
 [   14    35]]


# Pendências

AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'

Fim do curso.